# Generated by extendr: Do not edit by hand
#
# This file would normally be regenerated with `rextendr::document()` after
# changing the Rust source. It is checked in so the package is usable without
# the development toolchain. Keep it in sync with `src/rust/src/lib.rs`.

#' @docType package
#' @usage NULL
#' @useDynLib pubmedclient, .registration = TRUE
NULL

client_new <- function(api_key, email, tool, rate_limit, timeout_seconds) .Call(wrap__client_new, api_key, email, tool, rate_limit, timeout_seconds)

client_search_articles <- function(client, query, limit) .Call(wrap__client_search_articles, client, query, limit)

client_fetch_article <- function(client, pmid) .Call(wrap__client_fetch_article, client, pmid)

client_fetch_articles <- function(client, pmids) .Call(wrap__client_fetch_articles, client, pmids)

client_search_and_fetch <- function(client, query, limit) .Call(wrap__client_search_and_fetch, client, query, limit)

pmc_fetch_fulltext <- function(client, pmcid) .Call(wrap__pmc_fetch_fulltext, client, pmcid)

pmc_markdown <- function(client, pmcid) .Call(wrap__pmc_markdown, client, pmcid)
