/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Stateful iterator for streaming PubMed search results
 *
 * This iterator fetches articles in batches using NCBI's history server,
 * enabling efficient streaming of large result sets without loading all
 * articles into memory at once.
 *
 * Implements async iteration through the `next()` method. Use with
 * JavaScript's `Symbol.asyncIterator` for `for await...of` syntax.
 *
 * @example
 * ```typescript
 * const iterator = await client.searchWithHistory("covid-19", 100);
 * console.log(`Total results: ${iterator.totalCount}`);
 *
 * let article;
 * while ((article = await iterator.next()) !== null) {
 *   console.log(`${article.pmid}: ${article.title}`);
 *   console.log(`Progress: ${iterator.progress}/${iterator.totalCount}`);
 * }
 * ```
 */
export declare class ArticleIterator {
  /**
   * Get the next article from the iterator
   *
   * Returns the next article in the result set, automatically fetching
   * new batches from the history server as needed. Returns `null` when
   * all articles have been returned.
   *
   * @returns The next Article, or null when iteration is complete
   *
   * @example
   * ```typescript
   * const iterator = await client.searchWithHistory("cancer", 50);
   * let article;
   * while ((article = await iterator.next()) !== null) {
   *   console.log(article.title);
   * }
   * ```
   */
  next(): Promise<Article | null>
  /**
   * Check if iteration is complete
   *
   * @returns true if all articles have been returned, false otherwise
   */
  get isDone(): boolean
  /**
   * Get the total count of results matching the query
   *
   * This value is determined at search time and represents the total
   * number of articles available to iterate through.
   *
   * @returns Total number of matching articles
   */
  get totalCount(): number
  /**
   * Get the current progress (number of articles yielded so far)
   *
   * Useful for displaying progress indicators when iterating through
   * large result sets.
   *
   * @returns Number of articles that have been returned via next()
   */
  get progress(): number
}

/** PubMed/PMC API client */
export declare class PubMedClient {
  /** Create a new PubMed client with default configuration */
  constructor()
  /** Create a new PubMed client with custom configuration */
  static withConfig(config: Config): PubMedClient
  /**
   * Search PubMed and fetch article metadata
   *
   * @param query - Search query string (PubMed syntax supported)
   * @param limit - Maximum number of results to return
   * @returns Array of article metadata
   */
  search(query: string, limit?: number | undefined | null): Promise<Array<Article>>
  /**
   * Fetch a single article by PMID
   *
   * @param pmid - PubMed ID
   * @returns Article metadata
   */
  fetchArticle(pmid: string): Promise<Article>
  /**
   * Fetch full-text article from PMC
   *
   * @param pmcid - PMC ID (e.g., "PMC7906746")
   * @returns Full-text article data
   */
  fetchPmcArticle(pmcid: string): Promise<FullTextArticle>
  /**
   * Fetch PMC article and convert to Markdown
   *
   * @param pmcid - PMC ID (e.g., "PMC7906746")
   * @param options - Markdown conversion options
   * @returns Markdown string
   */
  fetchPmcAsMarkdown(pmcid: string, options?: MarkdownOptions | undefined | null): Promise<string>
  /**
   * Check if a PubMed article has full-text available in PMC
   *
   * @param pmid - PubMed ID
   * @returns PMC ID if available, null otherwise
   */
  checkPmcAvailability(pmid: string): Promise<string | null>
  /**
   * Check if a PMC article is in the OA (Open Access) subset
   *
   * The OA subset contains articles with programmatic access to full-text XML.
   * Some publishers restrict programmatic access even though the article may be
   * viewable on the PMC website.
   *
   * @param pmcid - PMC ID (e.g., "PMC7906746")
   * @returns OaSubsetInfo containing detailed information about OA availability
   *
   * @example
   * ```typescript
   * const client = new PubMedClient();
   * const info = await client.isOaSubset("PMC7906746");
   *
   * if (info.isOaSubset) {
   *     console.log("Article is in OA subset");
   *     console.log("Download:", info.downloadLink);
   * } else {
   *     console.log("Not in OA subset:", info.errorCode);
   * }
   * ```
   */
  isOaSubset(pmcid: string): Promise<OaSubsetInfo>
  /**
   * Execute a search query and return articles
   *
   * @param query - SearchQuery instance
   * @returns Array of article metadata
   */
  executeQuery(query: SearchQuery): Promise<Array<Article>>
  /**
   * Search PubMed and create a streaming iterator for results
   *
   * Uses NCBI's history server to enable efficient streaming of large result sets.
   * The returned `ArticleIterator` can be used to fetch articles one at a time,
   * automatically handling batch fetching and pagination.
   *
   * @param query - Search query string (PubMed syntax supported)
   * @param batchSize - Number of articles to fetch per batch (default: 100, recommended: 100-500)
   * @returns ArticleIterator for streaming results
   *
   * @example
   * ```typescript
   * const client = new PubMedClient();
   *
   * // Create iterator
   * const iterator = await client.searchWithHistory("COVID-19 vaccine", 100);
   * console.log(`Total results: ${iterator.totalCount}`);
   *
   * // Iterate manually
   * let article;
   * while ((article = await iterator.next()) !== null) {
   *     console.log(`${article.pmid}: ${article.title}`);
   *     console.log(`Progress: ${iterator.progress}/${iterator.totalCount}`);
   * }
   *
   * // Or use with Symbol.asyncIterator (requires wrapper)
   * for await (const article of iterator) {
   *     console.log(article.title);
   *     if (someCondition) break; // Can break early
   * }
   * ```
   */
  searchWithHistory(query: string, batchSize?: number | undefined | null): Promise<ArticleIterator>
}

/**
 * Builder for constructing PubMed search queries programmatically
 *
 * Provides a fluent API for building complex PubMed search queries with support for:
 * - Basic search terms
 * - Date filtering
 * - Article type and language filtering
 * - Open access filtering
 * - Boolean logic operations (AND, OR, NOT)
 * - MeSH terms and author filtering
 *
 * @example
 * ```typescript
 * const query = new SearchQuery()
 *   .query("covid-19")
 *   .publishedInYear(2024)
 *   .articleType("Clinical Trial")
 *   .freeFullTextOnly();
 *
 * const articles = await client.executeQuery(query);
 * ```
 */
export declare class SearchQuery {
  /** Create a new empty search query builder */
  constructor()
  /**
   * Add a search term to the query
   *
   * Terms are accumulated and will be space-separated in the final query.
   *
   * @param term - Search term string
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("covid-19")
   *   .query("treatment");
   * query.build(); // "covid-19 treatment"
   * ```
   */
  query(term: string): this
  /**
   * Add multiple search terms at once
   *
   * Each term is processed like query(). Empty strings are filtered out.
   *
   * @param terms - Array of search term strings
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .terms(["covid-19", "vaccine", "efficacy"]);
   * query.build(); // "covid-19 vaccine efficacy"
   * ```
   */
  terms(terms: Array<string>): this
  /**
   * Set the maximum number of results to return
   *
   * @param limit - Maximum number of results (clamped to 1-10,000 range)
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("cancer")
   *   .setLimit(50);
   * ```
   */
  setLimit(limit: number): this
  /**
   * Build the final PubMed query string
   *
   * @returns Query string for PubMed E-utilities API
   * @throws Error if no search terms have been added
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("covid-19")
   *   .query("treatment");
   * query.build(); // "covid-19 treatment"
   * ```
   */
  build(): string
  /**
   * Get the limit for this query
   *
   * @returns Maximum number of results (default: 20)
   *
   * @example
   * ```typescript
   * const query = new SearchQuery().query("cancer").limit(100);
   * query.getLimit(); // 100
   * ```
   */
  get limit(): number
  /**
   * Filter to articles published in a specific year
   *
   * @param year - Year to filter by (must be between 1800 and 3000)
   * @returns Self for method chaining
   * @throws Error if year is outside valid range
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("covid-19")
   *   .publishedInYear(2024);
   * ```
   */
  publishedInYear(year: number): this
  /**
   * Filter by publication date range
   *
   * @param startYear - Start year (inclusive)
   * @param endYear - End year (inclusive, optional)
   * @returns Self for method chaining
   * @throws Error if years are outside valid range
   *
   * @example
   * ```typescript
   * // Filter to 2020-2024
   * const query = new SearchQuery()
   *   .query("cancer")
   *   .publishedBetween(2020, 2024);
   *
   * // Filter from 2020 onwards
   * const query2 = new SearchQuery()
   *   .query("treatment")
   *   .publishedBetween(2020);
   * ```
   */
  publishedBetween(startYear: number, endYear?: number | undefined | null): this
  /**
   * Filter to articles published after a specific year
   *
   * @param year - Year after which articles were published
   * @returns Self for method chaining
   * @throws Error if year is outside valid range
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("crispr")
   *   .publishedAfter(2020);
   * ```
   */
  publishedAfter(year: number): this
  /**
   * Filter to articles published before a specific year
   *
   * @param year - Year before which articles were published
   * @returns Self for method chaining
   * @throws Error if year is outside valid range
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("genome")
   *   .publishedBefore(2020);
   * ```
   */
  publishedBefore(year: number): this
  /**
   * Filter by a single article type
   *
   * @param typeName - Article type (case-insensitive)
   *   Supported types: "Clinical Trial", "Review", "Systematic Review",
   *   "Meta-Analysis", "Case Reports", "Randomized Controlled Trial" (or "RCT"),
   *   "Observational Study"
   * @returns Self for method chaining
   * @throws Error if article type is not recognized
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("cancer")
   *   .articleType("Clinical Trial");
   * ```
   */
  articleType(typeName: string): this
  /**
   * Filter by multiple article types (OR logic)
   *
   * @param types - Array of article type names (case-insensitive)
   * @returns Self for method chaining
   * @throws Error if any article type is not recognized
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("treatment")
   *   .articleTypes(["RCT", "Meta-Analysis"]);
   * ```
   */
  articleTypes(types: Array<string>): this
  /**
   * Filter by language
   *
   * @param lang - Language name (case-insensitive)
   *   Supported: "English", "Japanese", "German", "French", "Spanish", etc.
   *   Unknown languages are passed through as custom values.
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("cancer")
   *   .language("English");
   * ```
   */
  language(lang: string): this
  /**
   * Filter to articles with free full text (open access)
   *
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("cancer")
   *   .freeFullTextOnly();
   * ```
   */
  freeFullTextOnly(): this
  /**
   * Filter to articles with full text links (including subscription-based)
   *
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("diabetes")
   *   .fullTextOnly();
   * ```
   */
  fullTextOnly(): this
  /**
   * Filter to articles with PMC full text
   *
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("genomics")
   *   .pmcOnly();
   * ```
   */
  pmcOnly(): this
  /**
   * Filter to articles that have abstracts
   *
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("genetics")
   *   .hasAbstract();
   * ```
   */
  hasAbstract(): this
  /**
   * Search in article titles only
   *
   * @param text - Title text to search for
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .titleContains("machine learning");
   * ```
   */
  titleContains(text: string): this
  /**
   * Search in article abstracts only
   *
   * @param text - Abstract text to search for
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .abstractContains("neural networks");
   * ```
   */
  abstractContains(text: string): this
  /**
   * Search in both title and abstract
   *
   * @param text - Text to search for in title or abstract
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .titleOrAbstract("CRISPR gene editing");
   * ```
   */
  titleOrAbstract(text: string): this
  /**
   * Filter by journal name
   *
   * @param name - Journal name to search for
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("cancer")
   *   .journal("Nature");
   * ```
   */
  journal(name: string): this
  /**
   * Filter by grant number
   *
   * @param grantNumber - Grant number to search for
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .grantNumber("R01AI123456");
   * ```
   */
  grantNumber(grantNumber: string): this
  /**
   * Filter by MeSH term
   *
   * @param term - MeSH term to filter by
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .meshTerm("Neoplasms");
   * ```
   */
  meshTerm(term: string): this
  /**
   * Filter by MeSH major topic
   *
   * @param term - MeSH term to filter by as a major topic
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .meshMajorTopic("Diabetes Mellitus, Type 2");
   * ```
   */
  meshMajorTopic(term: string): this
  /**
   * Filter by multiple MeSH terms
   *
   * @param terms - Array of MeSH terms to filter by
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .meshTerms(["Neoplasms", "Antineoplastic Agents"]);
   * ```
   */
  meshTerms(terms: Array<string>): this
  /**
   * Filter by MeSH subheading
   *
   * @param subheading - MeSH subheading to filter by
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .meshTerm("Diabetes Mellitus")
   *   .meshSubheading("drug therapy");
   * ```
   */
  meshSubheading(subheading: string): this
  /**
   * Filter by author name
   *
   * @param name - Author name to search for
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("machine learning")
   *   .author("Williams K");
   * ```
   */
  author(name: string): this
  /**
   * Filter by first author
   *
   * @param name - First author name to search for
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("cancer")
   *   .firstAuthor("Smith J");
   * ```
   */
  firstAuthor(name: string): this
  /**
   * Filter by last author
   *
   * @param name - Last author name to search for
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("genomics")
   *   .lastAuthor("Johnson M");
   * ```
   */
  lastAuthor(name: string): this
  /**
   * Filter by institution/affiliation
   *
   * @param institution - Institution name to search for
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("cardiology")
   *   .affiliation("Harvard Medical School");
   * ```
   */
  affiliation(institution: string): this
  /**
   * Filter by ORCID identifier
   *
   * @param orcidId - ORCID identifier to search for
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .orcid("0000-0001-2345-6789");
   * ```
   */
  orcid(orcidId: string): this
  /**
   * Filter to human studies only
   *
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("drug treatment")
   *   .humanStudiesOnly();
   * ```
   */
  humanStudiesOnly(): this
  /**
   * Filter to animal studies only
   *
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("preclinical research")
   *   .animalStudiesOnly();
   * ```
   */
  animalStudiesOnly(): this
  /**
   * Filter by age group
   *
   * @param ageGroup - Age group to filter by (e.g., "Child", "Adult", "Aged")
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("pediatric medicine")
   *   .ageGroup("Child");
   * ```
   */
  ageGroup(ageGroup: string): this
  /**
   * Add a custom filter
   *
   * @param filter - Custom filter string in PubMed syntax
   * @returns Self for method chaining
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("research")
   *   .customFilter("humans[mh]");
   * ```
   */
  customFilter(filter: string): this
  /**
   * Combine this query with another using AND logic
   *
   * @param other - Another SearchQuery to combine with
   * @returns New SearchQuery with combined logic
   *
   * @example
   * ```typescript
   * const q1 = new SearchQuery().query("covid-19");
   * const q2 = new SearchQuery().query("vaccine");
   * const combined = q1.and(q2);
   * combined.build(); // "(covid-19) AND (vaccine)"
   * ```
   */
  and(other: SearchQuery): SearchQuery
  /**
   * Combine this query with another using OR logic
   *
   * @param other - Another SearchQuery to combine with
   * @returns New SearchQuery with combined logic
   *
   * @example
   * ```typescript
   * const q1 = new SearchQuery().query("diabetes");
   * const q2 = new SearchQuery().query("hypertension");
   * const combined = q1.or(q2);
   * combined.build(); // "(diabetes) OR (hypertension)"
   * ```
   */
  or(other: SearchQuery): SearchQuery
  /**
   * Negate this query using NOT logic
   *
   * @returns New SearchQuery with NOT logic
   *
   * @example
   * ```typescript
   * const query = new SearchQuery().query("cancer").negate();
   * query.build(); // "NOT (cancer)"
   * ```
   */
  negate(): SearchQuery
  /**
   * Exclude articles matching the given query
   *
   * @param excluded - SearchQuery representing articles to exclude
   * @returns New SearchQuery with exclusion logic
   *
   * @example
   * ```typescript
   * const base = new SearchQuery().query("cancer treatment");
   * const exclude = new SearchQuery().query("animal studies");
   * const filtered = base.exclude(exclude);
   * filtered.build(); // "(cancer treatment) NOT (animal studies)"
   * ```
   */
  exclude(excluded: SearchQuery): SearchQuery
  /**
   * Add parentheses around the current query for grouping
   *
   * @returns New SearchQuery wrapped in parentheses
   *
   * @example
   * ```typescript
   * const query = new SearchQuery()
   *   .query("cancer")
   *   .or(new SearchQuery().query("tumor"))
   *   .group();
   * query.build(); // "((cancer) OR (tumor))"
   * ```
   */
  group(): SearchQuery
}

/** PubMed article metadata */
export interface Article {
  /** PubMed ID */
  pmid: string
  /** Article title */
  title: string
  /** List of authors */
  authors: Array<Author>
  /** Journal name */
  journal: string
  /** Publication date */
  pubDate: string
  /** DOI if available */
  doi?: string
  /** PMC ID if available */
  pmcId?: string
  /** Abstract text */
  abstractText?: string
  /** Article types (e.g., "Research Article", "Review") */
  articleTypes: Array<string>
  /** Keywords */
  keywords: Array<string>
}

/** Author information */
export interface Author {
  /** Full name of the author */
  fullName: string
  /** ORCID identifier if available */
  orcid?: string
  /** Primary affiliation */
  affiliation?: string
}

/** Configuration options for the PubMed client */
export interface Config {
  /** NCBI API key for higher rate limits */
  apiKey?: string
  /** Email address for NCBI identification */
  email?: string
  /** Tool name for NCBI identification */
  tool?: string
  /** Request timeout in seconds */
  timeoutSeconds?: number
}

/** Full-text article from PMC */
export interface FullTextArticle {
  /** PMC ID */
  pmcid: string
  /** PubMed ID if available */
  pmid?: string
  /** Article title */
  title: string
  /** List of authors */
  authors: Array<Author>
  /** Journal name */
  journal: string
  /** Publication date */
  pubDate: string
  /** DOI if available */
  doi?: string
  /** Article sections */
  sections: Array<Section>
  /** References */
  references: Array<Reference>
  /** Keywords */
  keywords: Array<string>
}

/** Markdown conversion options */
export interface MarkdownOptions {
  /** Include metadata header */
  includeMetadata?: boolean
  /** Include table of contents */
  includeToc?: boolean
  /** Use YAML frontmatter for metadata */
  useYamlFrontmatter?: boolean
  /** Include ORCID links for authors */
  includeOrcidLinks?: boolean
  /** Include figure captions */
  includeFigureCaptions?: boolean
}

/**
 * Information about OA (Open Access) subset availability for a PMC article
 *
 * The OA subset contains articles with programmatic access to full-text XML.
 * Not all PMC articles are in the OA subset - some publishers restrict programmatic access
 * even though the article may be viewable on the PMC website.
 */
export interface OaSubsetInfo {
  /** PMC ID (e.g., "PMC7906746") */
  pmcid: string
  /** Whether the article is in the OA subset */
  isOaSubset: boolean
  /** Citation string (if available) */
  citation?: string
  /** License type (if available) */
  license?: string
  /** Whether the article is retracted */
  retracted: boolean
  /** Download link for tar.gz package (if available) */
  downloadLink?: string
  /** Format of the download (e.g., "tgz", "pdf") */
  downloadFormat?: string
  /** Last updated timestamp for the download */
  updated?: string
  /** Error code if not in OA subset */
  errorCode?: string
  /** Error message if not in OA subset */
  errorMessage?: string
}

/** Reference information from PMC articles */
export interface Reference {
  /** Reference ID */
  id: string
  /** Reference title */
  title?: string
  /** Authors as a single string */
  authors: string
  /** Journal name */
  journal?: string
  /** Publication year */
  year?: string
  /** PubMed ID if available */
  pmid?: string
  /** DOI if available */
  doi?: string
}

/** Section of a PMC article */
export interface Section {
  /** Section type (e.g., "introduction", "methods") */
  sectionType: string
  /** Section title */
  title?: string
  /** Section content */
  content: string
}
