# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "Affiliation",
    "ApiException",
    "ArticleSection",
    "ArticleSummary",
    "Author",
    "CitationMatch",
    "CitationMatches",
    "CitationQuery",
    "Citations",
    "Client",
    "ClientConfig",
    "DatabaseCount",
    "DatabaseInfo",
    "EPostResult",
    "ExtractedFigure",
    "Figure",
    "GlobalQueryResults",
    "HistorySessionException",
    "InvalidQueryException",
    "OaSubsetInfo",
    "ParseException",
    "PmcAffiliation",
    "PmcAuthor",
    "PmcClient",
    "PmcFullText",
    "PmcLinks",
    "PubMedArticle",
    "PubMedClient",
    "PubMedException",
    "RateLimitException",
    "Reference",
    "RelatedArticles",
    "RequestException",
    "SearchLimitException",
    "SearchQuery",
    "SpellCheckResult",
    "Table",
    "__version__",
]

@typing.final
class Affiliation:
    r"""
    Python wrapper for Author affiliation
    """
    @property
    def institution(self) -> typing.Optional[builtins.str]: ...
    @property
    def department(self) -> typing.Optional[builtins.str]: ...
    @property
    def address(self) -> typing.Optional[builtins.str]: ...
    @property
    def country(self) -> typing.Optional[builtins.str]: ...
    @property
    def email(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ArticleSection:
    r"""
    Python wrapper for ArticleSection
    """
    @property
    def title(self) -> typing.Optional[builtins.str]: ...
    @property
    def content(self) -> builtins.str: ...
    @property
    def section_type(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ArticleSummary:
    r"""
    Lightweight article summary from the ESummary API

    Contains basic metadata (title, authors, journal, dates) without abstracts,
    MeSH terms, or chemical lists. Faster than PubMedArticle for bulk retrieval.

    Examples:
        >>> client = PubMedClient()
        >>> summaries = client.fetch_summaries(["31978945", "33515491"])
        >>> for s in summaries:
        ...     print(f"{s.pmid}: {s.title} ({s.pub_date})")
    """
    @property
    def pmid(self) -> builtins.str: ...
    @property
    def title(self) -> builtins.str: ...
    @property
    def authors(self) -> builtins.list[builtins.str]: ...
    @property
    def journal(self) -> builtins.str: ...
    @property
    def full_journal_name(self) -> builtins.str: ...
    @property
    def pub_date(self) -> builtins.str: ...
    @property
    def epub_date(self) -> builtins.str: ...
    @property
    def doi(self) -> typing.Optional[builtins.str]: ...
    @property
    def pmc_id(self) -> typing.Optional[builtins.str]: ...
    @property
    def volume(self) -> builtins.str: ...
    @property
    def issue(self) -> builtins.str: ...
    @property
    def pages(self) -> builtins.str: ...
    @property
    def languages(self) -> builtins.list[builtins.str]: ...
    @property
    def pub_types(self) -> builtins.list[builtins.str]: ...
    @property
    def issn(self) -> builtins.str: ...
    @property
    def essn(self) -> builtins.str: ...
    @property
    def sort_pub_date(self) -> builtins.str: ...
    @property
    def pmc_ref_count(self) -> builtins.int: ...
    @property
    def record_status(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Author:
    r"""
    Python wrapper for Author
    """
    @property
    def surname(self) -> typing.Optional[builtins.str]: ...
    @property
    def given_names(self) -> typing.Optional[builtins.str]: ...
    @property
    def initials(self) -> typing.Optional[builtins.str]: ...
    @property
    def suffix(self) -> typing.Optional[builtins.str]: ...
    @property
    def full_name(self) -> builtins.str: ...
    @property
    def orcid(self) -> typing.Optional[builtins.str]: ...
    @property
    def email(self) -> typing.Optional[builtins.str]: ...
    @property
    def is_corresponding(self) -> builtins.bool: ...
    def affiliations(self) -> typing.Any:
        r"""
        Get list of affiliations
        """
    def roles(self) -> typing.Any:
        r"""
        Get list of roles/contributions
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class CitationMatch:
    r"""
    Result of a single citation match from the ECitMatch API

    Attributes:
        journal: Journal title from the query
        year: Year from the query
        volume: Volume from the query
        first_page: First page from the query
        author_name: Author name from the query
        key: User-defined key from the query
        pmid: Matched PMID (None if not found)
        status: Match status ("found", "not_found", or "ambiguous")
    """
    @property
    def journal(self) -> builtins.str: ...
    @property
    def year(self) -> builtins.str: ...
    @property
    def volume(self) -> builtins.str: ...
    @property
    def first_page(self) -> builtins.str: ...
    @property
    def author_name(self) -> builtins.str: ...
    @property
    def key(self) -> builtins.str: ...
    @property
    def pmid(self) -> typing.Optional[builtins.str]: ...
    @property
    def status(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class CitationMatches:
    r"""
    Results from ECitMatch API for batch citation matching

    Attributes:
        matches: List of CitationMatch results
    """
    @property
    def matches(self) -> typing.Any:
        r"""
        Get the list of citation match results
        """
    def found_count(self) -> builtins.int:
        r"""
        Get the number of successful matches
        """
    def __repr__(self) -> builtins.str: ...
    def __len__(self) -> builtins.int: ...

@typing.final
class CitationQuery:
    r"""
    Input for a single citation match query

    Used with the ECitMatch API to find PMIDs from citation information
    (journal, year, volume, page, author).

    Examples:
        >>> query = CitationQuery(
        ...     journal="proc natl acad sci u s a",
        ...     year="1991",
        ...     volume="88",
        ...     first_page="3248",
        ...     author_name="mann bj",
        ...     key="Art1",
        ... )
    """
    @property
    def journal(self) -> builtins.str: ...
    @property
    def year(self) -> builtins.str: ...
    @property
    def volume(self) -> builtins.str: ...
    @property
    def first_page(self) -> builtins.str: ...
    @property
    def author_name(self) -> builtins.str: ...
    @property
    def key(self) -> builtins.str: ...
    def __new__(cls, journal: builtins.str, year: builtins.str, volume: builtins.str, first_page: builtins.str, author_name: builtins.str, key: builtins.str) -> CitationQuery: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Citations:
    r"""
    Python wrapper for Citations
    """
    @property
    def source_pmids(self) -> builtins.list[builtins.int]: ...
    @property
    def citing_pmids(self) -> builtins.list[builtins.int]: ...
    def __repr__(self) -> builtins.str: ...
    def __len__(self) -> builtins.int: ...

@typing.final
class Client:
    r"""
    Combined client with both PubMed and PMC functionality

    This is the main client you'll typically use. It provides access to both
    PubMed metadata searches and PMC full-text retrieval.

    Examples:
        >>> client = Client()
        >>> # Access PubMed client
        >>> articles = client.pubmed.search_and_fetch("covid-19", 10)
        >>> # Access PMC client
        >>> full_text = client.pmc.fetch_full_text("PMC7906746")
        >>> # Search with full text
        >>> results = client.search_with_full_text("covid-19", 5)
    """
    @property
    def pubmed(self) -> PubMedClient:
        r"""
        Get PubMed client for metadata operations
        """
    @property
    def pmc(self) -> PmcClient:
        r"""
        Get PMC client for full-text operations
        """
    def __new__(cls) -> Client:
        r"""
        Create a new combined client with default configuration
        """
    @staticmethod
    def with_config(config: ClientConfig) -> Client:
        r"""
        Create a new combined client with custom configuration
        """
    def search_with_full_text(self, query: builtins.str, limit: builtins.int) -> builtins.list[tuple[PubMedArticle, typing.Optional[PmcFullText]]]:
        r"""
        Search for articles and attempt to fetch full text for each

        This is a convenience method that searches PubMed and attempts to fetch
        PMC full text for each result when available.

        Args:
            query: Search query string
            limit: Maximum number of articles to process

        Returns:
            List of tuples (PubMedArticle, Optional[PmcFullText])
        """
    def get_database_list(self) -> builtins.list[builtins.str]:
        r"""
        Get list of all available NCBI databases
        """
    def get_database_info(self, database: builtins.str) -> DatabaseInfo:
        r"""
        Get detailed information about a specific database
        """
    def get_related_articles(self, pmids: typing.Sequence[builtins.int]) -> RelatedArticles:
        r"""
        Get related articles for given PMIDs
        """
    def get_pmc_links(self, pmids: typing.Sequence[builtins.int]) -> PmcLinks:
        r"""
        Get PMC links for given PMIDs
        """
    def get_citations(self, pmids: typing.Sequence[builtins.int]) -> Citations:
        r"""
        Get citing articles for given PMIDs
        """
    def spell_check(self, term: builtins.str) -> SpellCheckResult:
        r"""
        Check spelling of a search term using the ESpell API

        Provides spelling suggestions for terms within a single text query.
        Uses the PubMed database by default.

        Args:
            term: The search term to spell-check

        Returns:
            SpellCheckResult with the corrected query and details

        Examples:
            >>> client = Client()
            >>> result = client.spell_check("asthmaa")
            >>> print(result.corrected_query)
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ClientConfig:
    r"""
    Python wrapper for ClientConfig

    Configuration for PubMed and PMC clients.

    Examples:
        >>> config = ClientConfig()
        >>> config.with_api_key("your_api_key").with_email("you@example.com")
        >>> client = Client.with_config(config)
    """
    def __new__(cls) -> ClientConfig:
        r"""
        Create a new configuration with default settings
        """
    def with_api_key(self, api_key: builtins.str) -> ClientConfig:
        r"""
        Set the NCBI API key for increased rate limits (10 req/sec instead of 3)
        """
    def with_email(self, email: builtins.str) -> ClientConfig:
        r"""
        Set the email address for identification (recommended by NCBI)
        """
    def with_tool(self, tool: builtins.str) -> ClientConfig:
        r"""
        Set the tool name for identification (default: "pubmed-client-py")
        """
    def with_rate_limit(self, rate_limit: builtins.float) -> ClientConfig:
        r"""
        Set custom rate limit in requests per second
        """
    def with_timeout_seconds(self, timeout_seconds: builtins.int) -> ClientConfig:
        r"""
        Set HTTP request timeout in seconds
        """
    def with_cache(self) -> ClientConfig:
        r"""
        Enable default response caching
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class DatabaseCount:
    r"""
    Record count for a single NCBI database from the EGQuery API

    Attributes:
        db_name: Internal database name (e.g., "pubmed", "pmc")
        menu_name: Human-readable database name (e.g., "PubMed", "PMC")
        count: Number of matching records
        status: Query status (e.g., "Ok")
    """
    @property
    def db_name(self) -> builtins.str: ...
    @property
    def menu_name(self) -> builtins.str: ...
    @property
    def count(self) -> builtins.int: ...
    @property
    def status(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DatabaseInfo:
    r"""
    Python wrapper for DatabaseInfo
    """
    @property
    def name(self) -> builtins.str: ...
    @property
    def menu_name(self) -> builtins.str: ...
    @property
    def description(self) -> builtins.str: ...
    @property
    def build(self) -> typing.Optional[builtins.str]: ...
    @property
    def count(self) -> typing.Optional[builtins.int]: ...
    @property
    def last_update(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class EPostResult:
    r"""
    Python wrapper for EPostResult

    Result from EPost API for uploading PMIDs to the NCBI History server.
    Contains WebEnv and query_key identifiers for use with subsequent API calls.

    Attributes:
        webenv: WebEnv session identifier
        query_key: Query key for the uploaded IDs within the session

    Examples:
        >>> client = PubMedClient()
        >>> result = client.epost(["31978945", "33515491"])
        >>> print(f"WebEnv: {result.webenv}, Query Key: {result.query_key}")
    """
    @property
    def webenv(self) -> builtins.str: ...
    @property
    def query_key(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ExtractedFigure:
    r"""
    Python wrapper for ExtractedFigure

    Represents a figure that has been extracted from a PMC OA Cloud article,
    combining XML metadata with actual file information.
    """
    @property
    def figure(self) -> Figure:
        r"""
        Figure metadata from XML (caption, label, etc.)
        """
    @property
    def extracted_file_path(self) -> builtins.str:
        r"""
        Actual file path where the figure was extracted
        """
    @property
    def file_size(self) -> typing.Optional[builtins.int]:
        r"""
        File size in bytes
        """
    @property
    def dimensions(self) -> typing.Optional[tuple[builtins.int, builtins.int]]:
        r"""
        Image dimensions as (width, height) tuple if available
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Figure:
    r"""
    Python wrapper for Figure
    """
    @property
    def id(self) -> builtins.str: ...
    @property
    def label(self) -> typing.Optional[builtins.str]: ...
    @property
    def caption(self) -> typing.Optional[builtins.str]: ...
    @property
    def alt_text(self) -> typing.Optional[builtins.str]: ...
    @property
    def fig_type(self) -> typing.Optional[builtins.str]: ...
    @property
    def graphic_href(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class GlobalQueryResults:
    r"""
    Results from EGQuery API for global database search

    Attributes:
        term: The query term that was searched
        results: List of DatabaseCount results for each database
    """
    @property
    def term(self) -> builtins.str: ...
    @property
    def results(self) -> typing.Any:
        r"""
        Get the list of database count results
        """
    def non_zero(self) -> typing.Any:
        r"""
        Get results with count > 0
        """
    def count_for(self, db_name: builtins.str) -> typing.Optional[builtins.int]:
        r"""
        Get count for a specific database
        """
    def __repr__(self) -> builtins.str: ...
    def __len__(self) -> builtins.int: ...

@typing.final
class OaSubsetInfo:
    r"""
    Python wrapper for OaSubsetInfo

    Information about OA (Open Access) subset availability for a PMC article.
    The OA subset contains articles with programmatic access to full-text XML.
    """
    @property
    def pmcid(self) -> builtins.str:
        r"""
        PMC ID (e.g., "PMC7906746")
        """
    @property
    def is_oa_subset(self) -> builtins.bool:
        r"""
        Whether the article is in the OA subset
        """
    @property
    def citation(self) -> typing.Optional[builtins.str]:
        r"""
        Citation string (if available)
        """
    @property
    def license(self) -> typing.Optional[builtins.str]:
        r"""
        License type (if available)
        """
    @property
    def retracted(self) -> builtins.bool:
        r"""
        Whether the article is retracted
        """
    @property
    def download_link(self) -> typing.Optional[builtins.str]:
        r"""
        Download link for tar.gz package (if available)
        """
    @property
    def download_format(self) -> typing.Optional[builtins.str]:
        r"""
        Format of the download (e.g., "tgz", "pdf")
        """
    @property
    def updated(self) -> typing.Optional[builtins.str]:
        r"""
        Last updated timestamp for the download
        """
    @property
    def error_code(self) -> typing.Optional[builtins.str]:
        r"""
        Error code if not in OA subset
        """
    @property
    def error_message(self) -> typing.Optional[builtins.str]:
        r"""
        Error message if not in OA subset
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class PmcAffiliation:
    r"""
    Python wrapper for PMC Affiliation
    """
    @property
    def id(self) -> typing.Optional[builtins.str]: ...
    @property
    def institution(self) -> typing.Optional[builtins.str]: ...
    @property
    def department(self) -> typing.Optional[builtins.str]: ...
    @property
    def address(self) -> typing.Optional[builtins.str]: ...
    @property
    def country(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class PmcAuthor:
    r"""
    Python wrapper for PMC Author
    """
    @property
    def given_names(self) -> typing.Optional[builtins.str]: ...
    @property
    def surname(self) -> typing.Optional[builtins.str]: ...
    @property
    def full_name(self) -> builtins.str: ...
    @property
    def orcid(self) -> typing.Optional[builtins.str]: ...
    @property
    def email(self) -> typing.Optional[builtins.str]: ...
    @property
    def is_corresponding(self) -> builtins.bool: ...
    def affiliations(self) -> typing.Any:
        r"""
        Get list of affiliations
        """
    def roles(self) -> typing.Any:
        r"""
        Get list of roles/contributions
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class PmcClient:
    r"""
    PMC client for fetching full-text articles

    Examples:
        >>> client = PmcClient()
        >>> full_text = client.fetch_full_text("PMC7906746")
        >>> pmcid = client.check_pmc_availability("31978945")
    """
    def __new__(cls) -> PmcClient:
        r"""
        Create a new PMC client with default configuration
        """
    @staticmethod
    def with_config(config: ClientConfig) -> PmcClient:
        r"""
        Create a new PMC client with custom configuration
        """
    def fetch_full_text(self, pmcid: builtins.str) -> PmcFullText:
        r"""
        Fetch full text article from PMC

        Args:
            pmcid: PMC ID (e.g., "PMC7906746")

        Returns:
            PmcFullText object containing structured article content
        """
    def check_pmc_availability(self, pmid: builtins.str) -> typing.Optional[builtins.str]:
        r"""
        Check if a PubMed article has PMC full text available

        Args:
            pmid: PubMed ID as a string

        Returns:
            PMC ID if available, None otherwise
        """
    def download_files(self, pmcid: builtins.str, output_dir: builtins.str) -> list:
        r"""
        Download a PMC article's Open Access files

        Downloads each of the article's files individually from the PMC OA Cloud
        (AWS S3) service for the specified PMC ID into the output directory.

        Args:
            pmcid: PMC ID (e.g., "PMC7906746" or "7906746")
            output_dir: Directory path where files should be downloaded

        Returns:
            List of downloaded file paths

        Note:
            This method is only available on non-WASM platforms

        Example:
            >>> client = PmcClient()
            >>> files = client.download_files("PMC7906746", "./output")
            >>> for file in files:
            ...     print(file)
        """
    def extract_figures_with_captions(self, pmcid: builtins.str, output_dir: builtins.str) -> list:
        r"""
        Extract figures with captions from PMC article

        Downloads the article's files from the PMC OA Cloud (AWS S3) service,
        then matches figures with their captions from the XML metadata.

        Args:
            pmcid: PMC ID (e.g., "PMC7906746" or "7906746")
            output_dir: Directory path where files should be downloaded

        Returns:
            List of ExtractedFigure objects containing metadata and file information

        Note:
            This method is only available on non-WASM platforms

        Example:
            >>> client = PmcClient()
            >>> figures = client.extract_figures_with_captions("PMC7906746", "./output")
            >>> for fig in figures:
            ...     print(f"{fig.figure.id}: {fig.extracted_file_path}")
            ...     print(f"  Caption: {fig.figure.caption}")
            ...     print(f"  Size: {fig.file_size} bytes")
            ...     print(f"  Dimensions: {fig.dimensions}")
        """
    def is_oa_subset(self, pmcid: builtins.str) -> OaSubsetInfo:
        r"""
        Check if a PMC article is in the OA (Open Access) subset

        The OA subset contains articles with programmatic access to full-text XML.
        Some publishers restrict programmatic access even though the article may be
        viewable on the PMC website.

        Args:
            pmcid: PMC ID (with or without "PMC" prefix, e.g., "PMC7906746" or "7906746")

        Returns:
            OaSubsetInfo object containing detailed information about OA availability

        Example:
            >>> client = PmcClient()
            >>> oa_info = client.is_oa_subset("PMC7906746")
            >>> if oa_info.is_oa_subset:
            ...     print(f"Article is in OA subset")
            ...     if oa_info.download_link:
            ...         print(f"Download: {oa_info.download_link}")
            ... else:
            ...     print(f"Not in OA subset: {oa_info.error_message}")
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class PmcFullText:
    r"""
    Python wrapper for PmcFullText
    """
    @property
    def pmcid(self) -> builtins.str: ...
    @property
    def pmid(self) -> typing.Optional[builtins.str]: ...
    @property
    def title(self) -> typing.Optional[builtins.str]: ...
    @property
    def doi(self) -> typing.Optional[builtins.str]: ...
    def authors(self) -> typing.Any:
        r"""
        Get list of authors
        """
    def sections(self) -> typing.Any:
        r"""
        Get list of sections
        """
    def figures(self) -> typing.Any:
        r"""
        Get list of all figures from all sections
        """
    def tables(self) -> typing.Any:
        r"""
        Get list of all tables from all sections
        """
    def references(self) -> typing.Any:
        r"""
        Get list of references
        """
    def to_markdown(self) -> builtins.str:
        r"""
        Convert the article to Markdown format

        Returns:
            A Markdown-formatted string representation of the article

        Example:
            >>> full_text = client.pmc.fetch_full_text("PMC7906746")
            >>> markdown = full_text.to_markdown()
            >>> print(markdown)
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class PmcLinks:
    r"""
    Python wrapper for PmcLinks
    """
    @property
    def source_pmids(self) -> builtins.list[builtins.int]: ...
    @property
    def pmc_ids(self) -> builtins.list[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...
    def __len__(self) -> builtins.int: ...

@typing.final
class PubMedArticle:
    r"""
    Python wrapper for PubMedArticle
    """
    @property
    def pmid(self) -> builtins.str: ...
    @property
    def title(self) -> builtins.str: ...
    @property
    def journal(self) -> builtins.str: ...
    @property
    def pub_date(self) -> builtins.str: ...
    @property
    def doi(self) -> typing.Optional[builtins.str]: ...
    @property
    def pmc_id(self) -> typing.Optional[builtins.str]: ...
    @property
    def abstract_text(self) -> typing.Optional[builtins.str]: ...
    @property
    def author_count(self) -> builtins.int: ...
    @property
    def volume(self) -> typing.Optional[builtins.str]: ...
    @property
    def issue(self) -> typing.Optional[builtins.str]: ...
    @property
    def pages(self) -> typing.Optional[builtins.str]: ...
    @property
    def language(self) -> typing.Optional[builtins.str]: ...
    @property
    def journal_abbreviation(self) -> typing.Optional[builtins.str]: ...
    @property
    def issn(self) -> typing.Optional[builtins.str]: ...
    def authors(self) -> typing.Any:
        r"""
        Get list of authors
        """
    def article_types(self) -> typing.Any:
        r"""
        Get article types
        """
    def keywords(self) -> typing.Any:
        r"""
        Get keywords (empty list when none are present)
        """
    def to_bibtex(self) -> builtins.str:
        r"""
        Export the article as a BibTeX entry
        """
    def to_ris(self) -> builtins.str:
        r"""
        Export the article in RIS format
        """
    def to_nbib(self) -> builtins.str:
        r"""
        Export the article in MEDLINE/NBIB format
        """
    def to_csl_json(self) -> builtins.str:
        r"""
        Export the article as a CSL-JSON string
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class PubMedClient:
    r"""
    PubMed client for searching and fetching article metadata

    Examples:
        >>> client = PubMedClient()
        >>> articles = client.search_and_fetch("covid-19", 10)
        >>> article = client.fetch_article("31978945")
    """
    def __new__(cls) -> PubMedClient:
        r"""
        Create a new PubMed client with default configuration
        """
    @staticmethod
    def with_config(config: ClientConfig) -> PubMedClient:
        r"""
        Create a new PubMed client with custom configuration
        """
    def search_articles(self, query: builtins.str | SearchQuery, limit: builtins.int) -> builtins.list[builtins.str]:
        r"""
        Search for articles and return PMIDs only

        This method returns only the list of PMIDs matching the query,
        which is faster than fetching full article metadata.

        Args:
            query: Search query (either a string or SearchQuery object)
            limit: Maximum number of PMIDs to return (ignored if query is SearchQuery)

        Returns:
            List of PMIDs as strings

        Examples:
            >>> client = PubMedClient()
            >>> # Using string query
            >>> pmids = client.search_articles("covid-19", 100)
            >>> pmids = client.search_articles("cancer[ti] AND therapy[tiab]", 50)
            >>> # Using SearchQuery object
            >>> query = SearchQuery().query("covid-19").limit(100)
            >>> pmids = client.search_articles(query, 0)  # limit parameter ignored
        """
    def search_and_fetch(self, query: builtins.str | SearchQuery, limit: builtins.int) -> builtins.list[PubMedArticle]:
        r"""
        Search for articles and fetch their metadata

        Args:
            query: Search query (either a string or SearchQuery object)
            limit: Maximum number of articles to return (ignored if query is SearchQuery)

        Returns:
            List of PubMedArticle objects

        Examples:
            >>> client = PubMedClient()
            >>> # Using string query
            >>> articles = client.search_and_fetch("covid-19", 10)
            >>> # Using SearchQuery object
            >>> query = SearchQuery().query("cancer").published_after(2020).limit(50)
            >>> articles = client.search_and_fetch(query, 0)  # limit parameter ignored
        """
    def fetch_articles(self, pmids: typing.Sequence[builtins.str]) -> builtins.list[PubMedArticle]:
        r"""
        Fetch multiple articles by PMIDs in a single batch request

        This is significantly more efficient than fetching articles one by one,
        as it sends fewer HTTP requests to the NCBI API. For large numbers of PMIDs,
        the request is automatically split into batches of 200.

        Args:
            pmids: List of PubMed IDs as strings

        Returns:
            List of PubMedArticle objects

        Examples:
            >>> client = PubMedClient()
            >>> articles = client.fetch_articles(["31978945", "33515491", "25760099"])
            >>> for article in articles:
            ...     print(f"{article.pmid}: {article.title}")
        """
    def fetch_article(self, pmid: builtins.str) -> PubMedArticle:
        r"""
        Fetch a single article by PMID

        Args:
            pmid: PubMed ID as a string

        Returns:
            PubMedArticle object
        """
    def fetch_summaries(self, pmids: typing.Sequence[builtins.str]) -> builtins.list[ArticleSummary]:
        r"""
        Fetch lightweight article summaries by PMIDs using the ESummary API

        Returns basic metadata (title, authors, journal, dates, DOI) without
        abstracts, MeSH terms, or chemical lists. Faster than fetch_articles()
        for bulk metadata retrieval.

        Args:
            pmids: List of PubMed IDs as strings

        Returns:
            List of ArticleSummary objects

        Examples:
            >>> client = PubMedClient()
            >>> summaries = client.fetch_summaries(["31978945", "33515491"])
            >>> for s in summaries:
            ...     print(f"{s.pmid}: {s.title}")
        """
    def search_and_fetch_summaries(self, query: builtins.str | SearchQuery, limit: builtins.int) -> builtins.list[ArticleSummary]:
        r"""
        Search and fetch lightweight summaries in a single operation

        Combines search and ESummary fetch. Use this when you only need basic
        metadata and want faster retrieval than search_and_fetch().

        Args:
            query: Search query (either a string or SearchQuery object)
            limit: Maximum number of articles (ignored if query is SearchQuery)

        Returns:
            List of ArticleSummary objects

        Examples:
            >>> client = PubMedClient()
            >>> summaries = client.search_and_fetch_summaries("covid-19", 20)
            >>> for s in summaries:
            ...     print(f"{s.pmid}: {s.title}")
        """
    def get_database_list(self) -> builtins.list[builtins.str]:
        r"""
        Get list of all available NCBI databases

        Returns:
            List of database names
        """
    def get_database_info(self, database: builtins.str) -> DatabaseInfo:
        r"""
        Get detailed information about a specific database

        Args:
            database: Database name (e.g., "pubmed", "pmc")

        Returns:
            DatabaseInfo object
        """
    def get_related_articles(self, pmids: typing.Sequence[builtins.int]) -> RelatedArticles:
        r"""
        Get related articles for given PMIDs

        Args:
            pmids: List of PubMed IDs

        Returns:
            RelatedArticles object
        """
    def get_pmc_links(self, pmids: typing.Sequence[builtins.int]) -> PmcLinks:
        r"""
        Get PMC links for given PMIDs (full-text availability)

        Args:
            pmids: List of PubMed IDs

        Returns:
            PmcLinks object containing available PMC IDs
        """
    def get_citations(self, pmids: typing.Sequence[builtins.int]) -> Citations:
        r"""
        Get citing articles for given PMIDs

        Returns articles that cite the specified PMIDs from the PubMed database only.

        Important: Citation counts from this method may be LOWER than Google Scholar
        or scite.ai because this only includes peer-reviewed articles in PubMed.
        Other sources include preprints, books, and conference proceedings.

        Example: PMID 31978945 shows ~14,000 citations in PubMed vs ~23,000 in scite.ai.
        This is expected - this method provides PubMed-specific citation data.

        Args:
            pmids: List of PubMed IDs

        Returns:
            Citations object containing citing article PMIDs
        """
    def match_citations(self, citations: typing.Sequence[CitationQuery]) -> CitationMatches:
        r"""
        Match citations to PMIDs using the ECitMatch API

        Takes citation information (journal, year, volume, page, author)
        and returns corresponding PMIDs. Useful for identifying PMIDs
        from reference lists.

        Args:
            citations: List of CitationQuery objects

        Returns:
            CitationMatches object containing match results

        Examples:
            >>> client = PubMedClient()
            >>> queries = [
            ...     CitationQuery("proc natl acad sci u s a", "1991", "88", "3248", "mann bj", "Art1"),
            ...     CitationQuery("science", "1987", "235", "182", "palmenberg ac", "Art2"),
            ... ]
            >>> results = client.match_citations(queries)
            >>> for m in results.matches:
            ...     print(f"{m.key}: {m.pmid} ({m.status})")
        """
    def global_query(self, term: builtins.str) -> GlobalQueryResults:
        r"""
        Query all NCBI databases for record counts using the EGQuery API

        Returns the number of records matching the query in each
        Entrez database. Useful for exploratory searches.

        Args:
            term: Search query string

        Returns:
            GlobalQueryResults object containing counts per database

        Examples:
            >>> client = PubMedClient()
            >>> results = client.global_query("asthma")
            >>> for db in results.non_zero():
            ...     print(f"{db.menu_name}: {db.count}")
        """
    def epost(self, pmids: typing.Sequence[builtins.str]) -> EPostResult:
        r"""
        Upload a list of PMIDs to the NCBI History server using EPost

        Stores UIDs on the server and returns WebEnv/query_key identifiers
        that can be used with subsequent API calls for batch fetching.

        Args:
            pmids: List of PubMed IDs as strings

        Returns:
            EPostResult containing webenv and query_key

        Examples:
            >>> client = PubMedClient()
            >>> result = client.epost(["31978945", "33515491", "25760099"])
            >>> print(f"WebEnv: {result.webenv}")
            >>> print(f"Query Key: {result.query_key}")
        """
    def fetch_all_by_pmids(self, pmids: typing.Sequence[builtins.str]) -> builtins.list[PubMedArticle]:
        r"""
        Fetch all articles for a list of PMIDs using EPost and the History server

        Uploads the PMID list via EPost (HTTP POST), then fetches articles in
        paginated batches. Recommended for large PMID lists (hundreds or thousands).

        Args:
            pmids: List of PubMed IDs as strings

        Returns:
            List of PubMedArticle objects

        Examples:
            >>> client = PubMedClient()
            >>> articles = client.fetch_all_by_pmids(["31978945", "33515491", "25760099"])
            >>> for a in articles:
            ...     print(a.title)
        """
    def spell_check(self, term: builtins.str) -> SpellCheckResult:
        r"""
        Check spelling of a search term using the ESpell API

        Provides spelling suggestions for terms within a single text query.
        Uses the PubMed database by default.

        Args:
            term: The search term to spell-check

        Returns:
            SpellCheckResult with the corrected query and details

        Examples:
            >>> client = PubMedClient()
            >>> result = client.spell_check("asthmaa")
            >>> print(result.corrected_query)
            "asthma"
        """
    def spell_check_db(self, term: builtins.str, db: builtins.str) -> SpellCheckResult:
        r"""
        Check spelling of a search term against a specific database

        Spelling suggestions are database-specific, so use the same
        database you plan to search.

        Args:
            term: The search term to spell-check
            db: The NCBI database to check against (e.g., "pubmed", "pmc")

        Returns:
            SpellCheckResult with the corrected query and details

        Examples:
            >>> client = PubMedClient()
            >>> result = client.spell_check_db("fiberblast", "pmc")
            >>> print(result.corrected_query)
            "fibroblast"
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Reference:
    r"""
    Python wrapper for Reference
    """
    @property
    def id(self) -> builtins.str: ...
    @property
    def title(self) -> typing.Optional[builtins.str]: ...
    @property
    def source(self) -> typing.Optional[builtins.str]: ...
    @property
    def year(self) -> typing.Optional[builtins.str]: ...
    @property
    def pmid(self) -> typing.Optional[builtins.str]: ...
    @property
    def doi(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class RelatedArticles:
    r"""
    Python wrapper for RelatedArticles
    """
    @property
    def source_pmids(self) -> builtins.list[builtins.int]: ...
    @property
    def related_pmids(self) -> builtins.list[builtins.int]: ...
    @property
    def link_type(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
    def __len__(self) -> builtins.int: ...

@typing.final
class SearchQuery:
    r"""
    Python wrapper for SearchQuery

    Builder for constructing PubMed search queries programmatically.

    Examples:
        >>> query = SearchQuery().query("covid-19").limit(10)
        >>> query_string = query.build()
        >>> print(query_string)
        covid-19
    """
    def __new__(cls) -> SearchQuery:
        r"""
        Create a new empty search query builder

        Returns:
            SearchQuery: New query builder instance

        Example:
            >>> query = SearchQuery()
        """
    def query(self, term: typing.Optional[builtins.str] = None) -> SearchQuery:
        r"""
        Add a search term to the query

        Terms are accumulated (not replaced) and will be space-separated in the final query.
        None and empty strings (after trimming) are silently filtered out.

        Args:
            term: Search term string (None or empty strings are filtered)

        Returns:
            SearchQuery: Self for method chaining

        Example:
            >>> query = SearchQuery().query("covid-19").query("treatment")
            >>> query.build()
            'covid-19 treatment'
        """
    def terms(self, terms: typing.Optional[typing.Sequence[typing.Optional[builtins.str]]] = None) -> SearchQuery:
        r"""
        Add multiple search terms at once

        Each term is processed like query(). None items and empty strings are filtered out.

        Args:
            terms: List of search term strings

        Returns:
            SearchQuery: Self for method chaining

        Example:
            >>> query = SearchQuery().terms(["covid-19", "vaccine", "efficacy"])
            >>> query.build()
            'covid-19 vaccine efficacy'
        """
    def limit(self, limit: typing.Optional[builtins.int] = None) -> SearchQuery:
        r"""
        Set the maximum number of results to return

        Validates that limit is >0 and ≤10,000. None is treated as "use default" (20).

        Args:
            limit: Maximum number of results (None = use default of 20)

        Returns:
            SearchQuery: Self for method chaining

        Raises:
            ValueError: If limit ≤ 0 or limit > 10,000

        Example:
            >>> query = SearchQuery().query("cancer").limit(50)
        """
    def build(self) -> builtins.str:
        r"""
        Build the final PubMed query string

        Terms are joined with space separators (PubMed's default OR logic).

        Returns:
            str: Query string for PubMed E-utilities API

        Raises:
            ValueError: If no search terms have been added

        Example:
            >>> query = SearchQuery().query("covid-19").query("treatment")
            >>> query.build()
            'covid-19 treatment'
        """
    def get_limit(self) -> builtins.int:
        r"""
        Get the limit for this query

        Returns the configured limit or the default of 20 if not set.

        Returns:
            int: Maximum number of results (default: 20)

        Example:
            >>> query = SearchQuery().query("cancer").limit(100)
            >>> query.get_limit()
            100
            >>> query2 = SearchQuery().query("diabetes")
            >>> query2.get_limit()
            20
        """
    def __repr__(self) -> builtins.str:
        r"""
        String representation for debugging
        """
    def published_in_year(self, year: builtins.int) -> SearchQuery:
        r"""
        Filter to articles published in a specific year

        Args:
            year: Year to filter by (must be between 1800 and 3000)

        Returns:
            SearchQuery: Self for method chaining

        Raises:
            ValueError: If year is outside the valid range (1800-3000)

        Example:
            >>> query = SearchQuery().query("covid-19").published_in_year(2024)
            >>> query.build()
            'covid-19 AND 2024[pdat]'
        """
    def published_between(self, start_year: builtins.int, end_year: typing.Optional[builtins.int] = None) -> SearchQuery:
        r"""
        Filter by publication date range

        Filters articles published between start_year and end_year (inclusive).
        If end_year is None, filters from start_year onwards (up to year 3000).

        Args:
            start_year: Start year (inclusive, must be 1800-3000)
            end_year: End year (inclusive, optional, must be 1800-3000 if provided)

        Returns:
            SearchQuery: Self for method chaining

        Raises:
            ValueError: If years are outside valid range or start_year > end_year

        Example:
            >>> # Filter to 2020-2024
            >>> query = SearchQuery().query("cancer").published_between(2020, 2024)
            >>> query.build()
            'cancer AND 2020:2024[pdat]'

            >>> # Filter from 2020 onwards
            >>> query = SearchQuery().query("treatment").published_between(2020, None)
            >>> query.build()
            'treatment AND 2020:3000[pdat]'
        """
    def published_after(self, year: builtins.int) -> SearchQuery:
        r"""
        Filter to articles published after a specific year

        Equivalent to published_between(year, None).

        Args:
            year: Year after which articles were published (must be 1800-3000)

        Returns:
            SearchQuery: Self for method chaining

        Raises:
            ValueError: If year is outside the valid range (1800-3000)

        Example:
            >>> query = SearchQuery().query("crispr").published_after(2020)
            >>> query.build()
            'crispr AND 2020:3000[pdat]'
        """
    def published_before(self, year: builtins.int) -> SearchQuery:
        r"""
        Filter to articles published before a specific year

        Filters articles from 1900 up to and including the specified year.

        Args:
            year: Year before which articles were published (must be 1800-3000)

        Returns:
            SearchQuery: Self for method chaining

        Raises:
            ValueError: If year is outside the valid range (1800-3000)

        Example:
            >>> query = SearchQuery().query("genome").published_before(2020)
            >>> query.build()
            'genome AND 1900:2020[pdat]'
        """
    def article_type(self, type_name: builtins.str) -> SearchQuery:
        r"""
        Filter by a single article type

        Args:
            type_name: Article type name (case-insensitive)
                Supported types: "Clinical Trial", "Review", "Systematic Review",
                "Meta-Analysis", "Case Reports", "Randomized Controlled Trial" (or "RCT"),
                "Observational Study"

        Returns:
            SearchQuery: Self for method chaining

        Raises:
            ValueError: If article type is not recognized

        Example:
            >>> query = SearchQuery().query("cancer").article_type("Clinical Trial")
            >>> query.build()
            'cancer AND Clinical Trial[pt]'
        """
    def article_types(self, types: typing.Sequence[builtins.str]) -> SearchQuery:
        r"""
        Filter by multiple article types (OR logic)

        When multiple types are provided, they are combined with OR logic.
        Empty list is silently ignored (no filter added).

        Args:
            types: List of article type names (case-insensitive)

        Returns:
            SearchQuery: Self for method chaining

        Raises:
            ValueError: If any article type is not recognized

        Example:
            >>> query = SearchQuery().query("treatment").article_types(["RCT", "Meta-Analysis"])
            >>> query.build()
            'treatment AND (Randomized Controlled Trial[pt] OR Meta-Analysis[pt])'
        """
    def free_full_text_only(self) -> SearchQuery:
        r"""
        Filter to articles with free full text (open access)

        This includes articles that are freely available from PubMed Central
        and other open access sources.

        Returns:
            SearchQuery: Self for method chaining

        Example:
            >>> query = SearchQuery().query("cancer").free_full_text_only()
            >>> query.build()
            'cancer AND free full text[sb]'
        """
    def full_text_only(self) -> SearchQuery:
        r"""
        Filter to articles with full text links

        This includes both free full text and subscription-based full text articles.
        Use free_full_text_only() if you only want open access articles.

        Returns:
            SearchQuery: Self for method chaining

        Example:
            >>> query = SearchQuery().query("diabetes").full_text_only()
            >>> query.build()
            'diabetes AND full text[sb]'
        """
    def pmc_only(self) -> SearchQuery:
        r"""
        Filter to articles with PMC full text

        This filters to articles that have full text available in PubMed Central (PMC).

        Returns:
            SearchQuery: Self for method chaining

        Example:
            >>> query = SearchQuery().query("genomics").pmc_only()
            >>> query.build()
            'genomics AND pmc[sb]'
        """
    def and_(self, other: SearchQuery) -> SearchQuery:
        r"""
        Combine this query with another using AND logic

        Combines two queries by wrapping each in parentheses and joining with AND.
        If either query is empty, returns the non-empty query.
        The result uses the higher limit of the two queries.

        Args:
            other: Another SearchQuery to combine with

        Returns:
            SearchQuery: New query with combined logic

        Example:
            >>> q1 = SearchQuery().query("covid-19")
            >>> q2 = SearchQuery().query("vaccine")
            >>> combined = q1.and_(q2)
            >>> combined.build()
            '(covid-19) AND (vaccine)'

            >>> # Complex chaining
            >>> result = SearchQuery().query("cancer") \\
            ...     .and_(SearchQuery().query("treatment")) \\
            ...     .and_(SearchQuery().query("2024[pdat]"))
            >>> result.build()
            '((cancer) AND (treatment)) AND (2024[pdat])'
        """
    def or_(self, other: SearchQuery) -> SearchQuery:
        r"""
        Combine this query with another using OR logic

        Combines two queries by wrapping each in parentheses and joining with OR.
        If either query is empty, returns the non-empty query.
        The result uses the higher limit of the two queries.

        Args:
            other: Another SearchQuery to combine with

        Returns:
            SearchQuery: New query with combined logic

        Example:
            >>> q1 = SearchQuery().query("diabetes")
            >>> q2 = SearchQuery().query("hypertension")
            >>> combined = q1.or_(q2)
            >>> combined.build()
            '(diabetes) OR (hypertension)'

            >>> # Find articles about either condition
            >>> result = SearchQuery().query("cancer") \\
            ...     .or_(SearchQuery().query("tumor")) \\
            ...     .or_(SearchQuery().query("oncology"))
            >>> result.build()
            '((cancer) OR (tumor)) OR (oncology)'
        """
    def negate(self) -> SearchQuery:
        r"""
        Negate this query using NOT logic

        Wraps the current query with NOT operator.
        This is typically used in combination with other queries to exclude results.
        Returns an empty query if the current query is empty.

        Returns:
            SearchQuery: New query with NOT logic

        Example:
            >>> query = SearchQuery().query("cancer").negate()
            >>> query.build()
            'NOT (cancer)'

            >>> # More practical: exclude from search results
            >>> base = SearchQuery().query("treatment")
            >>> excluded = SearchQuery().query("animal studies").negate()
            >>> # (Note: use exclude() method for this pattern)
        """
    def exclude(self, excluded: SearchQuery) -> SearchQuery:
        r"""
        Exclude articles matching the given query

        Excludes results from this query that match the excluded query.
        This is the recommended way to filter out unwanted results.
        If either query is empty, returns the base query unchanged.

        Args:
            excluded: SearchQuery representing articles to exclude

        Returns:
            SearchQuery: New query with exclusion logic

        Example:
            >>> base = SearchQuery().query("cancer treatment")
            >>> exclude = SearchQuery().query("animal studies")
            >>> filtered = base.exclude(exclude)
            >>> filtered.build()
            '(cancer treatment) NOT (animal studies)'

            >>> # Exclude multiple types of studies
            >>> human_only = SearchQuery().query("therapy") \\
            ...     .exclude(SearchQuery().query("animal studies")) \\
            ...     .exclude(SearchQuery().query("in vitro"))
        """
    def group(self) -> SearchQuery:
        r"""
        Add parentheses around the current query for grouping

        Wraps the query in parentheses to control operator precedence in complex queries.
        Returns an empty query if the current query is empty.

        Returns:
            SearchQuery: New query wrapped in parentheses

        Example:
            >>> query = SearchQuery().query("cancer").or_(SearchQuery().query("tumor")).group()
            >>> query.build()
            '((cancer) OR (tumor))'

            >>> # Controlling precedence
            >>> q1 = SearchQuery().query("a").or_(SearchQuery().query("b")).group()
            >>> q2 = SearchQuery().query("c").or_(SearchQuery().query("d")).group()
            >>> result = q1.and_(q2)
            >>> result.build()
            '(((a) OR (b))) AND (((c) OR (d)))'
        """
    def sort(self, sort_order: builtins.str) -> SearchQuery:
        r"""
        Set the sort order for search results

        Controls how PubMed orders the search results. The default (when not specified)
        is relevance-based sorting.

        Args:
            sort_order: Sort order string (case-insensitive)
                Supported values: "relevance", "pub_date" (or "publication_date"),
                "author" (or "first_author"), "journal" (or "journal_name")

        Returns:
            SearchQuery: Self for method chaining

        Raises:
            ValueError: If sort order is not recognized

        Example:
            >>> query = SearchQuery().query("cancer").sort("pub_date")
            >>> # Results will be sorted by publication date (newest first)
        """

@typing.final
class SpellCheckResult:
    r"""
    Python wrapper for SpellCheckResult

    Attributes:
        database: The database that was queried
        query: The original query string
        corrected_query: The corrected/suggested query
        has_corrections: Whether any spelling corrections were made
        replacements: List of corrected terms

    Examples:
        >>> client = PubMedClient()
        >>> result = client.spell_check("asthmaa")
        >>> print(result.corrected_query)
        "asthma"
        >>> result.has_corrections
        True
    """
    @property
    def database(self) -> builtins.str: ...
    @property
    def query(self) -> builtins.str: ...
    @property
    def corrected_query(self) -> builtins.str: ...
    @property
    def has_corrections(self) -> builtins.bool: ...
    @property
    def replacements(self) -> builtins.list[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Table:
    r"""
    Python wrapper for Table
    """
    @property
    def id(self) -> builtins.str: ...
    @property
    def label(self) -> typing.Optional[builtins.str]: ...
    @property
    def caption(self) -> typing.Optional[builtins.str]: ...
    def __repr__(self) -> builtins.str: ...

# --- Manually maintained (spliced in by `stub_gen.rs`) ------------------------
# `pyo3-stub-gen` cannot introspect `m.add(...)` / `create_exception!`, so the
# module version and the exception hierarchy are declared here. Keep in sync
# with `src/lib.rs` and `src/utils.rs`; CI verifies via `stubtest`.

__version__: builtins.str

class PubMedException(builtins.Exception):
    r"""Base exception for all PubMed client errors."""

class ParseException(PubMedException):
    r"""XML or JSON parsing failed."""

class RequestException(PubMedException):
    r"""HTTP request failed (network, timeout, DNS)."""

class InvalidQueryException(PubMedException):
    r"""Invalid query structure or parameters."""

class RateLimitException(PubMedException):
    r"""API rate limit exceeded (HTTP 429)."""

class ApiException(PubMedException):
    r"""API returned an error HTTP status code."""

class SearchLimitException(PubMedException):
    r"""Requested result count exceeds the maximum retrievable limit."""

class HistorySessionException(PubMedException):
    r"""History server session expired or WebEnv unavailable."""
